import { Link } from 'react-router-dom';
import PageTransition from '../components/PageTransition';
import '../assessment.css';
const ninds = 'https://www.ninds.nih.gov/current-research/focus-disorders/parkinsons-disease-research/parkinsons-disease-challenges-progress-and-promise';
const conditions = [
  ['Essential tremor', 'Tremor can overlap with Parkinson’s presentations. A specialist considers its pattern and the rest of the examination.', 'https://www.nice.org.uk/guidance/ng71/chapter/recommendations', 'NICE guidance'],
  ['Other neurodegenerative parkinsonism', 'Multiple system atrophy, progressive supranuclear palsy, corticobasal degeneration and Lewy body dementia can share features with Parkinson’s.', ninds, 'NINDS overview'],
  ['Secondary parkinsonism', 'Medication-related and vascular causes are among the alternatives considered during clinical assessment.', 'https://www.ncbi.nlm.nih.gov/books/NBK536714/table/Ch8-t0001/?report=objectonly', 'Clinical differential reference'],
  ['Other causes of tremor', 'Dystonic and functional tremor, medicines, and metabolic causes can produce shaking without establishing Parkinson’s disease.', 'https://www.ninds.nih.gov/sites/default/files/2025-05/Tremor.pdf', 'NINDS tremor guide'],
  ['Normal pressure hydrocephalus', 'Walking difficulties and other symptoms can complicate assessment. Clinical history and examination guide the differential.', 'https://medlineplus.gov/ency/article/000752.htm', 'MedlinePlus'],
  ['Voice and drawing changes', 'An abnormal recording or drawing is not specific to one disease. This binary training set does not represent the full range of clinical alternatives.', null, null],
];
export default function ClinicalContext() {
  return <PageTransition><div className="assessment-page"><header className="assessment-heading"><div><span className="eyebrow">CLINICAL CONTEXT • REFERENCE ONLY</span><h1>Similar symptoms.<br /><span>Different explanations.</span></h1><p>A voice or drawing classifier cannot establish the cause of a symptom. This page describes common overlapping conditions; it is not an exhaustive differential or an automated diagnosis.</p></div></header><div className="session-notice">This application only learned healthy-labelled versus Parkinson’s-labelled examples. It has no trained classes for the conditions below and cannot rule them in or out.</div><div className="context-grid">{conditions.map(([title, description, url, source]) => <article key={title} className="evidence-card"><h2>{title}</h2><p>{description}</p>{url && <a href={url} target="_blank" rel="noreferrer">{source} ↗</a>}</article>)}</div><section className="session-panel evidence-copy"><h2>Keep the clinical question separate</h2><p>NICE recommends clinical diagnosis and specialist assessment when Parkinson’s is suspected. A healthy-like model result does not exclude disease; a Parkinson’s-like result does not establish it. <a href="https://www.nice.org.uk/guidance/ng71/chapter/recommendations" target="_blank" rel="noreferrer">Read the diagnostic guidance</a>.</p><p>The assessment workspace records technical quality flags and reviewer observations. It does not turn those observations into disease predictions or medication recommendations.</p><Link to="/assessment" className="btn btn-outline">Return to assessment</Link></section></div></PageTransition>;
}
