import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import PageTransition from '../components/PageTransition';
import { fetchEvidence } from '../services/api';
import '../assessment.css';
const pct = value => value == null ? 'Not established' : `${(value * 100).toFixed(1)}%`;
export default function Evidence() {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; fetchEvidence().then(value => { if (active) setData(value); }).catch(err => { if (active) setError(err.message); }); return () => { active = false; }; }, []);
  return <PageTransition><div className="assessment-page">
    <header className="assessment-heading"><div><span className="eyebrow">METHODS • MEASUREMENTS • LIMITS</span><h1>Evidence before<br /><span>confidence.</span></h1><p>What the models have actually been tested on, what changed during the audit, and what remains unproven.</p></div><Link to="/assessment" className="btn btn-primary">Open assessment</Link></header>
    {error && <p className="analysis-error" role="alert">{error}</p>}
    {!data && !error && <p role="status">Loading model evidence…</p>}
    {data && <>
      <div className="session-notice">Paired three-test cohort: <strong>{data.fusion.paired_cohort_size}</strong>. Combined clinical accuracy: <strong>not established</strong>. The percentages below measure classification on particular dataset splits, not accuracy in a clinic.</div>
      <div className="evidence-cards">{Object.entries(data.models).map(([kind, model]) => <article className="evidence-card" key={kind}><span className="eyebrow">{model.loaded ? 'AVAILABLE' : 'UNAVAILABLE'}</span><h2>{model.name}</h2><div className="metric">{pct(model.accuracy)}</div><p>Dataset classification accuracy</p><dl><dt>Development / test</dt><dd>{model.train_count ?? '—'} / {model.test_count ?? '—'}</dd><dt>Sensitivity</dt><dd>{pct(model.sensitivity)}</dd><dt>Specificity</dt><dd>{pct(model.specificity)}</dd></dl><p>{model.limitations}</p><p>Clinical calibration: none.</p><details><summary>Model version details</summary><small>Evaluation matches this model: {model.evaluation_matches_artifact ? 'verified' : 'unavailable'}<br />SHA-256: {model.sha256 || 'not loaded'}</small></details><details><summary>Confusion matrix</summary><p>Rows: true healthy, PD. Columns: predicted healthy, PD.</p><code>{JSON.stringify(model.confusion_matrix)}</code></details></article>)}</div>
      <section className="session-panel evidence-copy"><h2>Fine-tuning, measured honestly</h2><p>We retrained the drawing heads, then tested low-learning-rate fine-tuning. Training, validation and test sets use disjoint filename-derived groups. These are an unverified proxy for participant identity. Stage selection uses validation log loss; the test set is evaluated after selection. These experimental models are not used for your assessments.</p><div className="table-scroll"><table className="evidence-table"><thead><tr><th>Candidate</th><th>Selected stage</th><th>Train / validation / test</th><th>Test accuracy</th><th>Sensitivity / specificity</th><th>Used in app?</th></tr></thead><tbody>{Object.entries(data.fine_tuning).map(([kind, experiment]) => <tr key={kind}><td>{kind}</td><td>{experiment.selected_stage.replaceAll('_',' ')}</td><td>{experiment.train_count} / {experiment.validation_count} / {experiment.test_count}</td><td>{pct(experiment.test_metrics.accuracy)}</td><td>{pct(experiment.test_metrics.sensitivity)} / {pct(experiment.test_metrics.specificity)}</td><td>{experiment.deployed ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div><p>The split differs from the original 80% drawing evaluation, so the numbers are not a controlled model comparison. The tiny test sets and uncertain subject identifiers limit the conclusions. No improvement or clinical readiness is claimed.</p></section>
      <section className="session-panel evidence-copy"><h2>What the dataset audit found</h2><p>The drawing development folders contain 72 images each; the supplied scripts reserve 14 for validation and fit the head on 58. Full historical epoch logs for the original saved models are unavailable.</p><p>{data.dataset.voice_filenames} audio filenames contain {data.dataset.unique_voice_recordings} unique recordings. Exact duplicates were removed before training and testing the voice model. Each drawing task has 102 images. The older UCI CSV has precomputed acoustic features; it is a separate experiment and cannot be substituted for the recording-based model.</p><p>There is no verified voice–spiral–wave mapping for the same participants. Randomly matching files would manufacture a cohort and invalidate a combined-performance claim.</p><h3>What a paired study needs</h3><p>Collect all available tests from each consenting participant with a pseudonymous participant and session code, acquisition protocol and independently supplied clinical reference label. Keep every session from one person in the same split. Learn weights on development data, calibrate on separate data, and evaluate once on untouched participants, including relevant comparison conditions.</p><a className="btn btn-outline" href="/paired-cohort-template.csv" download>Download empty cohort template</a></section>
    </>}
    <section className="session-panel evidence-copy"><h2>Transparent integration methods</h2><p><strong>Linear integration:</strong> L = Σwᵢpᵢ. <strong>Cobb–Douglas:</strong> G = ∏pᵢ^wᵢ, with A = 1, nonnegative weights summing to one. The assessment shows both, each test’s contribution, and a leave-one-test-out sensitivity check.</p><p><strong>Reviewer importance:</strong> adjustable weights, initially equal. These are exploratory preferences, not learned clinical importance. Spiral and wave may be correlated; adding them does not establish independent evidence.</p><p><strong>Minimizing error:</strong> audit leakage, match training and serving preprocessing, use validation-based model selection, and expose sensitivity, specificity and errors. More training alone does not guarantee better generalization.</p><p><a href="/methodology.md" download>Download full methodology</a> · <Link to="/clinical-context">Conditions with overlapping symptoms</Link> · <Link to="/about">About this project</Link></p><p>Technical references: <a href="https://arxiv.org/abs/1705.09406" target="_blank" rel="noreferrer">Multimodal machine learning survey</a>, <a href="https://www.tensorflow.org/guide/keras/transfer_learning" target="_blank" rel="noreferrer">TensorFlow transfer learning</a>, <a href="https://scikit-learn.org/stable/modules/calibration.html" target="_blank" rel="noreferrer">Probability calibration</a>.</p></section>
  </div></PageTransition>;
}
