import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, AudioLines, Fingerprint, Waves, ScanLine, Sparkles, ShieldCheck, Pause, Play, Plus, MoveDown } from 'lucide-react';
import PageTransition from '../components/PageTransition';
import NeuralOrb from '../components/NeuralOrb';
import BrainArtwork from '../components/BrainArtwork';
const tests = [
  { number: '01', title: 'Voice', subtitle: 'Listen beyond the surface.', copy: 'Explore acoustic patterns in a short recording, with 193 extracted features and a trained voting ensemble.', route: '/voice', Icon: AudioLines, art: 'voice' },
  { number: '02', title: 'Spiral', subtitle: 'Every line tells a story.', copy: 'Compare a hand-drawn spiral with patterns learned by a dedicated image classifier.', route: '/spiral', Icon: Fingerprint, art: 'spiral' },
  { number: '03', title: 'Wave', subtitle: 'See the rhythm of movement.', copy: 'Add a second drawing perspective with a separate model trained on wave examples.', route: '/wave', Icon: Waves, art: 'wave' },
];
const faqs = [
  ['Can NeuroScan diagnose Parkinson’s disease?', 'No. It compares samples with labelled training examples. Neither individual classifications nor combined indices establish or exclude a diagnosis. Clinical interpretation requires an appropriately qualified professional.'],
  ['Do I need all three tests?', 'You can analyse one test independently. Two or three contributing tests enable the experimental combined indices. Missing tests are shown explicitly and never filled with invented results.'],
  ['What happens to my files?', 'The analysis backend processes uploads without creating a patient history. Temporary decoded audio is removed. You choose whether to export a report. AI chat is separate: only conversation text you explicitly submit is sent to Google.'],
  ['Is the combined result another trained model?', 'No. Three independent classifiers produce class scores. A weighted average and a weighted geometric mean then combine those scores. Neither formula has been clinically validated on a paired cohort.'],
];
export default function Home() {
  const [paused, setPaused] = useState(false);
  return <PageTransition><div className="premium-home">
    <section className="p-hero">
      <div className="hero-grid-line" aria-hidden="true" />
      <div className="p-hero-copy"><span className="p-kicker"><span className="status-dot" /> MULTIMODAL PARKINSON’S RESEARCH</span>
        <h1>A clearer view.<br />Of <em>every signal.</em></h1>
        <p>Voice. Movement. Perspective.<br />Explore three independent models in one thoughtful workspace, with evidence you can actually inspect.</p>
        <div className="p-actions"><Link to="/assessment" className="p-button primary">Begin assessment <ArrowUpRight size={19} /></Link><Link to="/evidence" className="p-button ghost">Explore the evidence <ArrowRight size={17} /></Link></div>
        <div className="hero-footnote"><ShieldCheck size={15} /> Built for research. Designed for human review.</div>
      </div>
      <div className="p-hero-art"><NeuralOrb paused={paused} /><div className="orb-coordinate top">NEURAL FIELD / 001<span>THREE INPUTS. A SHARED VIEW.</span></div><div className="orb-label label-voice"><AudioLines size={15} /> VOICE</div><div className="orb-label label-spiral"><Fingerprint size={15} /> SPIRAL</div><div className="orb-label label-wave"><Waves size={15} /> WAVE</div><div className="orb-bottom"><span>ABSTRACT SIGNAL VISUALIZATION</span><button type="button" onClick={() => setPaused(!paused)} aria-label={paused ? 'Play visual animation' : 'Pause visual animation'}>{paused ? <Play size={14} /> : <Pause size={14} />}</button></div></div>
      <div className="p-hero-bottom"><span>UNDERSTAND THE SIGNAL. RESPECT THE UNCERTAINTY.</span><a href="#perspectives" aria-label="Explore the three perspectives"><MoveDown size={18} /></a></div>
    </section>
    <section className="p-strip"><div><strong>03</strong><span>Independent classifiers</span></div><div><strong>02</strong><span>Transparent fusion methods</span></div><div><strong>01</strong><span>Connected research workspace</span></div><p>No hidden clinical claims.<br /><Link to="/evidence">See methods & limitations <ArrowUpRight size={13} /></Link></p></section>
    <section className="p-section" id="perspectives"><div className="p-section-head"><div><span className="p-kicker">01 / THE PERSPECTIVES</span><h2>Different signals.<br /><span>A fuller conversation.</span></h2></div><p>Each test has its own model.<br />Each result keeps its context.</p></div><div className="p-test-grid">{tests.map(({ number, title, subtitle, copy, route, Icon, art }) => <Link to={route} className="p-test-card" key={title}><div className="p-card-top"><span>{number} / {title.toUpperCase()}</span><ArrowUpRight size={21} /></div><div className={`signal-art ${art}`} aria-hidden="true">{art === 'voice' ? Array.from({ length: 37 }, (_, i) => <i key={i} style={{ '--bar': `${12 + Math.abs(Math.sin(i * .82) * Math.sin(i * .17)) * 84}%`, '--delay': `${i * .04}s` }} />) : art === 'spiral' ? <svg viewBox="0 0 240 140"><path d="M120 72c-3-12 16-14 20-1 6 22-30 34-43 9-21-40 45-68 70-25 34 60-59 110-105 47C9 28 135-37 195 40c69 88-71 159-139 93" /></svg> : <svg viewBox="0 0 240 140"><path d="M0 74C20 74 12 20 32 20s12 100 32 100 12-100 32-100 12 100 32 100 12-100 32-100 12 100 32 100 12-100 32-100 12 54 32 54" /></svg>}</div><Icon size={23} /><h3>{subtitle}</h3><p>{copy}</p><span className="p-card-link">Explore {title.toLowerCase()} analysis <ArrowRight size={15} /></span></Link>)}</div></section>
    <section className="p-section brain-feature" aria-labelledby="brain-feature-title">
      <BrainArtwork />
      <div className="brain-feature-copy"><span className="p-kicker">BEHIND EVERY SIGNAL, A PERSON</span><h2 id="brain-feature-title">Patterns are a start.<br /><em>Context matters.</em></h2><p>A voice recording or a drawing captures one small part of a much bigger picture. NeuroScan brings those observations into view while keeping their limits visible.</p><div className="brain-review-note"><ShieldCheck size={21} /><div><h3>Designed for thoughtful review.</h3><p>Explore the model evidence, understand overlapping symptoms, and prepare better questions for a qualified clinician.</p></div></div><Link to="/clinical-context" className="p-button ghost">Explore clinical context <ArrowUpRight size={17} /></Link></div>
    </section>
    <section className="p-integration p-section"><div><span className="p-kicker">02 / THE BIGGER PICTURE</span><h2>Bring the evidence<br /><em>into focus.</em></h2><p>Collect samples from one session. Explore relative importance. Compare linear and Cobb–Douglas indices without losing sight of the individual results.</p><Link to="/assessment" className="p-button primary">Open the workspace <ArrowUpRight size={18} /></Link></div><div className="integration-preview"><div className="preview-heading"><ScanLine size={20} /><span>THE ASSESSMENT FLOW</span><span className="small-dot" /></div><div className="preview-inputs"><span><AudioLines />Voice</span><span><Fingerprint />Spiral</span><span><Waves />Wave</span></div><div className="flow-line" /><div className="formula-preview"><span>Linear integration<strong>Σ wᵢpᵢ</strong></span><span>Cobb–Douglas<strong>∏ pᵢ<sup>wᵢ</sup></strong></span></div><div className="preview-end"><ShieldCheck size={18} /><span>Individual evidence. Adjustable weights.<br /><strong>One transparent review report.</strong></span></div><small>Illustration of the workflow. No patient result is shown.</small></div></section>
    <section className="p-section p-assistant-teaser"><div className="assistant-symbol"><Sparkles size={40} /></div><span className="p-kicker">03 / MAKE ROOM FOR QUESTIONS</span><h2>Understanding starts<br />with a <em>good question.</em></h2><p>Explore medical concepts, understand research scores, and prepare questions for a clinician with the medical information assistant.</p><Link to="/assistant" className="p-button primary">Meet the assistant <ArrowUpRight size={18} /></Link><small>AI information, not a diagnosis. Available when the provider is connected.</small></section>
    <section className="p-section p-faq"><div><span className="p-kicker">A LITTLE MORE CLARITY</span><h2>Before you<br /><span>begin.</span></h2><Link to="/clinical-context">Explore clinical context <ArrowUpRight size={16} /></Link></div><div>{faqs.map(([q, a]) => <details key={q}><summary>{q}<Plus size={18} /></summary><p>{a}</p></details>)}<a href="/model-guide.md" className="guide-download" download>Download the plain-language model guide <ArrowUpRight size={17} /></a></div></section>
    <section className="p-end"><span className="p-kicker">CURIOUS MINDS. CLEARER EVIDENCE.</span><h2>Take a closer look.</h2><Link to="/assessment" className="p-button light">Begin an assessment <ArrowUpRight size={18} /></Link></section>
  </div></PageTransition>;
}
