// Requires the local frontend/backend and Playwright (or NEUROSCAN_PLAYWRIGHT_MODULE).
const { chromium } = require(process.env.NEUROSCAN_PLAYWRIGHT_MODULE || 'playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const report = {checks:[], errors:[], results:[]};
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream',`--use-file-for-fake-audio-capture=${path.join(root,'test_samples/healthy_voice_1.wav')}`]});
 try {
  const context = await browser.newContext({viewport:{width:1440,height:1000},permissions:['microphone']});
  const page = await context.newPage();
  page.on('pageerror',error=>report.errors.push(error.message));
  await page.goto('http://localhost:5173/assessment');
  const analyse = page.getByRole('button',{name:'Analyse session',exact:true});
  assert.equal(await analyse.isDisabled(),true);
  await page.getByLabel('Upload spiral',{exact:true}).setInputFiles(path.join(root,'test_samples/healthy_spiral_2.png'));
  assert.equal(await analyse.isDisabled(),true);
  await page.getByRole('checkbox').check();
  assert.equal(await analyse.isEnabled(),true);
  report.checks.push('Same-person confirmation required before analysis');
  await page.getByText('Try bundled examples',{exact:true}).click();
  await page.getByLabel('Demo sample number').selectOption('2');
  for (const label of ['healthy','parkinson']) {
   await page.getByLabel('Demo label').selectOption(label);
   await page.getByRole('button',{name:'Load demo files',exact:true}).click();
   await page.getByText(`${label}_wave_2.png`,{exact:true}).waitFor();
   assert.equal(await page.getByLabel('Session purpose').inputValue(),'demo');
   const responsePromise=page.waitForResponse(r=>r.url().endsWith('/assessments')&&r.request().method()==='POST');
   await analyse.click();
   const response=await responsePromise;
   const result=await response.json();
   assert.equal(response.status(),200,JSON.stringify(result));
   await page.getByTestId('linear-index').waitFor();
   assert.equal(await page.getByTestId('linear-index').innerText(),result.fusion.linear.toFixed(3));
   assert.equal(await page.getByTestId('geometric-index').innerText(),result.fusion.cobb_douglas.toFixed(3));
   assert.ok(Object.values(result.results).every(r=>r.status===(label==='healthy'?0:1)));
   report.results.push({label,linear:result.fusion.linear,geometric:result.fusion.cobb_douglas});
   report.checks.push(`${label} demo: all three real models, matching displayed fusion scores`);
  }
  await page.getByLabel('voice weight',{exact:true}).fill('10');
  assert.equal(await page.getByRole('button',{name:'Export JSON',exact:true}).isDisabled(),true);
  await page.getByRole('status').filter({hasText:'Inputs or settings changed'}).waitFor();
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/assessments')&&r.request().method()==='POST');
  await analyse.click();
  const changed=await (await responsePromise).json();
  assert.equal(changed.fusion.effective_weights.voice,10/12);
  await page.getByRole('button',{name:'Export JSON',exact:true}).waitFor();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export JSON',exact:true}).click();
  const downloaded=await downloadPromise;
  const exported=JSON.parse(fs.readFileSync(await downloaded.path(),'utf8'));
  assert.equal(exported.assessment_id,changed.assessment_id);
  assert.equal(exported.fusion.clinical_probability,null);
  report.checks.push('Weight changes invalidate reports; reanalysis/export preserve exact server provenance');
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForTimeout(700);
  await page.screenshot({path:path.join(root,'reports/enhancement/assessment-desktop.png'),fullPage:true});
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('form').isVisible(),false);
  assert.equal(await page.getByTestId('linear-index').isVisible(),true);
  await page.pdf({path:path.join(root,'reports/enhancement/demo-report.pdf'),format:'A4',printBackground:true});
  await page.emulateMedia({media:'screen'});
  report.checks.push('Print report hides input controls and preserves report');
  await page.getByRole('button',{name:'Clear session',exact:true}).click();
  assert.equal(await page.getByRole('region',{name:'Assessment report'}).count(),0);
  await page.getByRole('button',{name:'Record voice',exact:true}).click();
  await page.getByRole('button',{name:/Stop recording/}).waitFor();
  await page.waitForTimeout(3500);
  await page.getByRole('button',{name:/Stop recording/}).click();
  await page.getByText('recording.webm',{exact:true}).waitFor();
  await page.getByRole('checkbox').check();
  const recordedPromise=page.waitForResponse(r=>r.url().endsWith('/assessments')&&r.request().method()==='POST');
  await analyse.click();
  const recorded=await (await recordedPromise).json();
  assert.ok(recorded.results.voice);
  assert.equal(recorded.fusion.linear,null);
  report.checks.push('Simulated microphone records, decodes and produces individual-only voice result');
  await page.getByRole('button',{name:'Clear session',exact:true}).click();
  await page.getByLabel('Upload spiral',{exact:true}).setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('bad')});
  await page.getByRole('alert').filter({hasText:'Choose a valid image'}).waitFor();
  report.checks.push('Invalid file displays inline error without losing page');
  await page.goto('http://localhost:5173/evidence');
  await page.getByText('96.5%',{exact:true}).waitFor();
  await page.getByText('70.4%',{exact:true}).waitFor();
  await page.getByText('66.7%',{exact:true}).waitFor();
  assert.equal((await page.request.get('http://localhost:5173/methodology.md')).status(),200);
  assert.equal((await page.request.get('http://localhost:5173/paired-cohort-template.csv')).status(),200);
  await page.screenshot({path:path.join(root,'reports/enhancement/evidence-desktop.png'),fullPage:true});
  await page.goto('http://localhost:5173/clinical-context');
  await page.getByRole('heading',{name:'Essential tremor',exact:true}).waitFor();
  report.checks.push('Evidence page shows live artifact metrics and candidate results; clinical reference and downloads render');
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://localhost:5173/assessment');
  await page.getByRole('heading',{name:'Collect the evidence'}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  const nav=await page.locator('.navbar').boundingBox(), heading=await page.locator('.assessment-heading').boundingBox();
  assert.ok(heading.y>=nav.y+nav.height,JSON.stringify({nav,heading}));
  await page.waitForTimeout(800);
  await page.screenshot({path:path.join(root,'reports/enhancement/assessment-mobile.png'),fullPage:true});
  report.checks.push('390px mobile layout fits viewport and heading clears navigation');
  assert.deepEqual(report.errors,[]);
  fs.writeFileSync(path.join(root,'reports/enhancement/browser-check.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
 } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
