const { chromium }=require(process.env.NEUROSCAN_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), report={checks:[],errors:[],chat:'Provider responses mocked for UI contract tests; live Google AI Studio replies are checked separately in live-chat-check.json and public-polish-check.json.'};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',error=>report.errors.push(error.message));
 await page.goto('http://localhost:5173/');await page.waitForTimeout(1000);
 await page.getByRole('heading',{name:'A clearer view. Of every signal.'}).waitFor();
 assert.equal(await page.locator('.neural-orb').count(),1);
 await page.getByRole('button',{name:'Pause visual animation'}).click();
 await page.getByRole('button',{name:'Play visual animation'}).waitFor();
 await page.screenshot({path:path.join(root,'reports/premium/home-desktop.png')});
 await page.screenshot({path:path.join(root,'reports/premium/home-full.png'),fullPage:true});
 report.checks.push('Homepage renders neural visual, animation pause and responsive editorial layout');
 await page.getByText('Can NeuroScan diagnose Parkinson’s disease?',{exact:true}).click();
 assert.ok(await page.getByText('No. It compares samples',{exact:false}).isVisible());
 const guide=await page.request.get('http://localhost:5173/model-guide.md');
 assert.equal(guide.status(),200);assert.ok((await guide.text()).includes('58 fitting images and 14 validation images'));
 await page.goto('http://localhost:5173/evidence');await page.getByRole('heading',{name:'Transparent integration methods'}).waitFor();
 assert.ok(!(await page.locator('body').innerText()).includes('teacher'));
 report.checks.push('Public methods wording cleaned; model guide downloads');
 await page.route('**/assistant/status',r=>r.fulfill({json:{configured:true}}));
 await page.goto('http://localhost:5173/assistant');await page.getByLabel('Your medical question').waitFor();
 await page.waitForTimeout(600);
 await page.screenshot({path:path.join(root,'reports/premium/assistant-desktop.png'),fullPage:true});
 await page.getByLabel('Your medical question').fill('How do the models work?');
 assert.equal(await page.getByRole('checkbox').count(),0);
 assert.ok(await page.getByText('By sending, you share your message',{exact:false}).isVisible());
 assert.ok(await page.getByRole('button',{name:'Send question'}).isEnabled());
 let requestBody;
 await page.route('**/assistant/chat',async route=>{requestBody=route.request().postDataJSON();await route.fulfill({json:{answer:'There are three independent classifier pipelines. The two combined indices are mathematical formulas, not an additional trained diagnostic model.',references:[{title:'NICE guidance',url:'https://www.nice.org.uk/guidance/ng71/chapter/recommendations'}]}});});
 await page.getByRole('button',{name:'Send question'}).click();
 await page.getByText('There are three independent classifier pipelines.',{exact:false}).waitFor();
 assert.equal(requestBody.consent,true);assert.deepEqual(Object.keys(requestBody).sort(),['consent','messages']);
 assert.equal(await page.locator('.chat-message').count(),2);
 await page.getByLabel('Your medical question').fill('And what about the drawings?');await page.getByRole('button',{name:'Send question'}).click();await page.waitForFunction(()=>document.querySelectorAll('.chat-message').length===4);
 assert.deepEqual(requestBody.messages.map(m=>m.role),['user','assistant','user']);
 report.checks.push('Chat discloses Google processing beside Send without a checkbox, sends only text, preserves bounded conversation, renders curated reading');
 await page.unroute('**/assistant/chat');await page.route('**/assistant/chat',r=>r.fulfill({status:503,json:{detail:'The AI connection needs attention.'}}));
 await page.getByLabel('Your medical question').fill('What is a tremor?');await page.getByRole('button',{name:'Send question'}).click();await page.getByRole('alert').filter({hasText:'AI connection needs attention'}).waitFor();
 assert.equal(await page.getByLabel('Your medical question').inputValue(),'What is a tremor?');assert.equal(await page.locator('.chat-message').count(),4);
 await page.getByRole('button',{name:'Clear conversation'}).click();assert.equal(await page.locator('.chat-message').count(),0);
 report.checks.push('Provider failure is explicit, preserves unsent question, adds no fabricated answer; clear resets conversation');
 await page.setViewportSize({width:390,height:844});
 for(const route of ['','assistant','assessment','voice','evidence']){
  await page.goto('http://localhost:5173/'+route);await page.waitForTimeout(750);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${route} overflow`);
  const nav=await page.locator('.navbar').boundingBox(),heading=await page.locator('h1,h2').first().boundingBox();assert.ok(heading.y>=nav.y+nav.height,`${route} heading clipped`);
  await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('navigation').getByRole('link',{name:'Assistant',exact:true}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'false');
  if(route===''||route==='assistant')await page.screenshot({path:path.join(root,`reports/premium/${route||'home'}-mobile.png`),fullPage:true});
 }
 report.checks.push('390px layouts fit viewport on five routes; mobile menu and Escape work');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('http://localhost:5173/');await page.waitForTimeout(700);assert.ok(await page.locator('.neural-orb').isVisible());
 report.checks.push('Reduced-motion mode preserves static neural visual and content');
 assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(root,'reports/premium/browser-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
